# Build a container via the command
#      > make dockerbname="247meeting" build
# Need to ensure the Docker daemon is running before the build will run

all:: build

build:
	docker build --rm -t irati/demobase .
